### ISSUE TITLE
Webhook unable to create new servicenow incident and always just updates the same one

### ISSUE THREAD

**Issue by swatikher** [FXinnovation/alertmanager-webhook-servicenow#31]
<img width="971" alt="Screen Shot 2020-09-13 at 2 17 39 PM" src="https://user-images.githubusercontent.com/13840978/93030229-4228d480-f5d6-11ea-8bb8-24ae7b5a3fba.png">

Using curl command - I fired multiple different alerts, alert groups, multiple different descriptions to webhook - but every time, webhook "GET" call always returns over 8000 matching existing incidents and it always just updates the same incident over and over. 

Same incident updated if a new alert is fired from Alertmanager as well.

Question:

1) Is there a way to always just create a brand new servicenow incident ?

2) Is there a way to not execute the GET call - it is time-consuming and it should not check for existing incidents

3) Is there a way to not do an update - because right now it is updating the wrong incident altogether and we have no way to stop the webhook from making that update

Here is the console output:

Sep 13 22:26:59 swati2.vexxhost.local alertmanager-webhook-servicenow[13999]: time="2020-09-13T22:26:59Z" level=info msg="Found updatable incident (IN001146079), with state 1, for firing alert group key: 3448373dc878a0ac5afd20195e740d9b" source="main.go:352"
Sep 13 22:26:59 swati2.vexxhost.local alertmanager-webhook-servicenow[13999]: time="2020-09-13T22:26:59Z" level=info msg="Update 1 field(s) of ServiceNow incident with id : 24fd623bdbefb3807e090e41ca9619e2" source="servicenow.go:229"
Sep 13 22:27:23 swati2.vexxhost.local alertmanager-webhook-servicenow[13999]: time="2020-09-13T22:27:23Z" level=info msg="Incident IN001146079 updated" source="servicenow.go:251"
Sep 13 22:28:56 swati2.vexxhost.local alertmanager-webhook-servicenow[13999]: time="2020-09-13T22:28:56Z" level=info msg="Found 10000 existing incident(s) for alert group key: cc25b13306b37d4422d54c9f6922efc1." source="main.go:312"
Sep 13 22:28:56 swati2.vexxhost.local alertmanager-webhook-servicenow[13999]: time="2020-09-13T22:28:56Z" level=info msg="Found 8098 updatable incident(s) for alert group key: cc25b13306b37d4422d54c9f6922efc1." source="main.go:315"
Sep 13 22:28:56 swati2.vexxhost.local alertmanager-webhook-servicenow[13999]: time="2020-09-13T22:28:56Z" level=warning msg="As multiple updable incidents were found for alert group key: cc25b13306b37d4422d54c9f6922efc1, first one will be used: IN001146079" source="main.go:322"
Sep 13 22:28:56 swati2.vexxhost.local alertmanager-webhook-servicenow[13999]: time="2020-09-13T22:28:56Z" level=error msg="'urgency' field value is <no value> but should be an integer, please fix your configuration. Incident creation/update will proceed but this field will be missing." source="main.go:396"
Sep 13 22:28:56 swati2.vexxhost.local alertmanager-webhook-servicenow[13999]: time="2020-09-13T22:28:56Z" level=info msg="Found updatable incident (IN001146079), with state 1, for firing alert group key: cc25b13306b37d4422d54c9f6922efc1" source="main.go:352"
Sep 13 22:28:56 swati2.vexxhost.local alertmanager-webhook-servicenow[13999]: time="2020-09-13T22:28:56Z" level=info msg="Update 1 field(s) of ServiceNow incident with id : 24fd623bdbefb3807e090e41ca9619e2" source="servicenow.go:229"
Sep 13 22:29:19 swati2.vexxhost.local alertmanager-webhook-servicenow[13999]: time="2020-09-13T22:29:19Z" level=info msg="Incident IN001146079 updated" source="servicenow.go:251"

**Comment by louisfelix** [comment]
Hi Swati,

What is the cURL command you are using?

As documented [here](https://github.com/FXinnovation/alertmanager-webhook-servicenow#manual-testing), the key for the webhook to decide to update or create an incident is the `groupLabels` field.

For instance, if your cURL data body is:
`{"receiver": "abc", "status": "firing", "externalURL":"http://my.url", "alerts": [{"status": "firing", "labels": {"alertname": "TestAlert1"}, "annotations":{"summary": "My alert summary", "description": "My description"} }], "groupLabels": {"alertname": "TestAlert1"}, "commonAnnotations": {"description": "My description"} }`

the webhook will take the `groupLabels` (here it is: `{"alertname": "TestAlert1"}`), it will calculate a hash key from it and will search in ServiceNow for this existing key (using the `incident_group_key_field` you chose in your config file. This ServiceNow field is important, it must exist in your ServiceNow incident table, and only the webhook should write to it to avoid weird behavior. If you currently don't have a ServieNow field dedicated to the webhook key ID, you can temporarily use the `description` field just to test.

I guess this is the reason why you receive so much incident from the webhook search for an existing incident with the same key (the GET), maybe the `incident_group_key_field` you chose in your config does not exist in the incident table.

Usually the GET, will retrieve only 0 or 1 incident, leading respectively to the creation of a new incident or update of an existing one.

Fixing your `incident_group_key_field` is the most important thing you should do.

So, 
1) No, not directly, but if your `groupLabel` contains something unique, such as a timestamp, you would create the behaviour of always creating a new incident. To manually test that, change a value in your `groupLabel` (TestAlert1, TestAlert2, TestAlert3, etc)

2) No, but if `incident_group_key_field` properly configured with an existing incident table field, the GET should be very fast, especially in your case as it will never return any result if your `groupLabel` is unique between calls.

3) See number 1). Also, to be sure you never do an update, there is a config for that. Change the following config so that whatever the incident state that was found from the search (GET), it won't update:
`no_update_states: [1,2,3,4,5,6,7,8,9]`. 
But be sure you fix 1) and 2) before, so that you fix your performance issue.

**Comment by swatikher** [comment]
Hi - Thanks for the info.  The curl command I'm using is this one (i've updated the groupLabel for a new alert named 'ZEKEALERT'

[1]+  Done                    curl -H "Content-type: application/json" -X POST -d '{"receiver": "web.hook", "status": "firing", "alerts": [{"status": "firing", "labels": {"alertname": "ZEKEALERT"}, "annotations":{"summary": "ZEKEALERT", "description": "ZEKEALERT"} }], "groupLabels": {"alertname": "ZEKEALERT"}, "commonAnnotations": {"description": "ZEKEALERT"} }' http://38.108.68.149:9877/webhook

it is returning {"Status":200,"Message":"Success"}

**Comment by swatikher** [comment]
Thanks Louis.  I changed the groupLabel to "INSTACL". I ensured that the incident_group_key_field is valid and existing incident table field.  I also set the no_update_states to [1,2,3,4,5,6,7,8,9]. And this time i ran the following curl command 

curl -H "Content-type: application/json" -X POST  -d '{"receiver": "web.hook", "status": "firing", "alerts": [{"status": "firing", "labels": {"alertname": "INSTACL"}, "annotations":{"summary": "INSTACL", "description": "INSTACL"} }], "groupLabels": {"alertname": "INSTACL"}, "commonAnnotations": {"description": "INSTACL"} }' http://38.108.68.149:9877/webhook

But the webhook still updates an existing incident

Sep 14 12:56:28 swati2.vexxhost.local alertmanager-webhook-servicenow[26147]: time="2020-09-14T12:56:28Z" level=info msg="Found 10000 existing incident(s) for alert group key: d34b359a7fc24daa28b528274392a15e." source="main.go:312"
Sep 14 12:56:28 swati2.vexxhost.local alertmanager-webhook-servicenow[26147]: time="2020-09-14T12:56:28Z" level=info msg="Found 1 updatable incident(s) for alert group key: d34b359a7fc24daa28b528274392a15e." source="main.go:315"
Sep 14 12:56:28 swati2.vexxhost.local alertmanager-webhook-servicenow[26147]: time="2020-09-14T12:56:28Z" level=error msg="'urgency' field value is <no value> but should be an integer, please fix your configuration. Incident creation/update will proceed but this field will be missing." source="main.go:396"
Sep 14 12:56:28 swati2.vexxhost.local alertmanager-webhook-servicenow[26147]: time="2020-09-14T12:56:28Z" level=info msg="Found updatable incident (IN19001155303), with state , for firing alert group key: d34b359a7fc24daa28b528274392a15e" source="main.go:352"
Sep 14 12:56:28 swati2.vexxhost.local alertmanager-webhook-servicenow[26147]: time="2020-09-14T12:56:28Z" level=info msg="Update 1 field(s) of ServiceNow incident with id : 875133a4dbe040507e090e41ca961964" source="servicenow.go:229"
Sep 14 12:56:29 swati2.vexxhost.local alertmanager-webhook-servicenow[26147]: time="2020-09-14T12:56:29Z" level=info msg="Incident IN19001155303 updated" source="servicenow.go:251"

**Comment by louisfelix** [comment]
Did you restart the webhook after your config change?

Also, to test more easily, maybe use the "description" field as your `incident_group_key_field`, and after the incident have been updated, make sure you see the hash key in the description.

**Comment by swatikher** [comment]
Thanks for the info Louis!  We have fixed the issue now from our side. The webhook is working now as expected and no further changes are required! Thank you for all of the helpful information!

**Comment by louisfelix** [comment]
Hi Swati, I am happy to read that, take care!
